name: Azure function infra CI/CD Feature
on:
  push:
    branches: [ feature/* ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'cdk/aws/**'
      - 'software/infrastructure/aws/**'
      - '.github/workflows/**-aws.yml'
  workflow_dispatch:

jobs:
  call-workflow-build-deploy:
    uses: ./.github/workflows/workflow-build-deploy-azure.yml
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_storage_account_name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      azure_storage_account_access_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_ACCESS_KEY }}